
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 02 03:04:48 ICT 2017
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 6;
  public static final int LTE = 25;
  public static final int LPAREN = 7;
  public static final int SEMI = 2;
  public static final int INT = 16;
  public static final int ECHO = 36;
  public static final int FOR = 18;
  public static final int MINUS = 4;
  public static final int RPAREN = 8;
  public static final int NOT = 33;
  public static final int AND = 34;
  public static final int LT = 24;
  public static final int OR = 35;
  public static final int BOOL = 17;
  public static final int COMMA = 22;
  public static final int ENDFOR = 19;
  public static final int PLUS = 3;
  public static final int MAIN = 32;
  public static final int IF = 10;
  public static final int ID = 41;
  public static final int ENDWHILE = 15;
  public static final int BOOLEAN = 40;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NEWLINE = 37;
  public static final int EQEQ = 28;
  public static final int NUMBER = 38;
  public static final int NEQ = 29;
  public static final int EQ = 9;
  public static final int GTE = 27;
  public static final int ENDPROC = 31;
  public static final int TIMES = 5;
  public static final int FLOATINGNUMBER = 39;
  public static final int COLON = 21;
  public static final int ENDIF = 12;
  public static final int ELSE = 11;
  public static final int WHILE = 14;
  public static final int FLOAT = 20;
  public static final int PROC = 30;
  public static final int GT = 26;
  public static final int VAR = 23;
  public static final int PRINT = 13;
}

